export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_CUSTOMERS = 'FETCH_USERS'
export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const FETCH_TODOS = 'FETCH_TODOS'
export const FETCH_APPS = 'FETCH_APPS'

export const UPDATE_SALE_NUMBER = 'UPDATE_SALE_NUMBER'

export const POST_NETWORK_ERROR = 'POST_NETWORK_ERROR'