// const URI_HOST = ''https://jsonplaceholder.typicode.com/'
const URI_HOST = 'http://localhost:3001'
export const URI_FETCH_USERS = URI_HOST + '/users'
export const URI_FETCH_CUSTOMERS = URI_HOST + '/customers'
export const URI_FETCH_TODOS = URI_HOST + '/todos'
export const URI_FETCH_PHOTOS = URI_HOST + '/photos'
export const URI_FETCH_POSTS = URI_HOST + '/posts'
export const URI_FETCH_APPS = URI_HOST + '/apps'